export enum CrochetTypes {
    Amigurumi = "amigurumi",
    AranCrochet = "aran_crochet",
    BavarianCrochet = "bavarian_crochet",
    BosnianCrochet = "bosnian_crochet",
    BullionCrochet = "bullion_crochet",
    BroomstickCrochet = "broomstick_crochet",
    BrugesCrochet = "bruges_crochet",
    ClotheslineCrochet = "clothesline_crochet",
    ClonesLaceCrochet = "clones_lace_crochet",
    CroHookCrochet = "cro_hook_crochet",
    C2C = "c2c", // Corner to corner crochet
    FilletCrochet = "fillet_crochet",
    FingerCrochet = "finger_crochet",
    FreeformCrochet = "freeform_crochet",
    HairpinCrochet = "hairpin_crochet",
    MicroCrochet = "micro_crochet",
    Mosiac = "mosiac",
    OverlayCrochet = "overlay_crochet",
    PineappleCrochet = "pineapple_crochet",
    StainedGlassCrochet = "stained_glass_crochet",
    TapestryCrochet = "tapestry_crochet",
    Tunesian = "tunesian",
}