export enum Tags {
  Clothing = "clothing",
  Hat = "hat",
  Scarf = "scarf",
  Amigurumi = "amigurumi",
  Gloves = "gloves",
  Socks = "socks",
  Keychain = "keychain",
  Beanie = "beanie",
  Pillow = "pillow",
  Blanket = "blanket",
  Bag = "bag",
  Coaster = "coaster",
  Drink_Accessory = "drink_accessory",
  Pet_Clothes = "pet_clothes",
  Cushon = "cushon",
  Purse = "purse",
  Other = "other",
}
